Add campus_access_files to bibdata alma machines
pulibrary/princeton_ansible pull request #2332
Opened 2021-06-24 20:51 UTC by eliotjordan

Closes https://github.com/pulibrary/bibdata/issues/1418

2021-06-24 20:55 UTC, hackartisan requested changes

2021-06-24 20:55 UTC, hackartisan commented on playbooks/bibdata_alma_staging.yml
> -    samba_shares_root: /data
don't we need this somewhere? Either here or in the group_vars file?

2021-06-24 21:21 UTC, eliotjordan commented
@hackartisan Ready for re-review.

2021-06-25 13:00 UTC, hackartisan approved these changes
👍🏻

2021-06-25 13:00 UTC, merged