[Bibdata] fix write errors
pulibrary/princeton_ansible pull request #2338
Opened 2021-06-29 16:13 UTC by hackartisan

fixes pulibrary/bibdata#1457

The smb.conf file was somehow coming up with 511 file and directory permissions even though we had configuration and a default value asking it to do otherwise. We ended up just hard-coding these values because there isn't a use case for any other value on any of our boxes.

2021-06-29 17:24 UTC, tpendragon requested changes
This looks fine, CI is just failing for bibdata.

2021-06-30 13:00 UTC, hackartisan commented
@tpendragon, @kayiwa fixed it; give another look?

2021-06-30 13:20 UTC, kayiwa approved these changes
OK!

2021-06-30 16:13 UTC, tpendragon approved these changes

2021-06-30 16:13 UTC, merged