Removes Cicognara from inventory files
pulibrary/princeton_ansible pull request #5655
Opened 2024-12-20 18:49 UTC by dphillips-39

Co-authored-by: Vickie Karasic <vickiekarasic@users.noreply.github.com>
Co-authored-by: Angel Ruiz <aruiz1789@users.noreply.github.com>

2025-01-07 15:19 UTC, kayiwa commented on roles/libstatic/defaults/main.yml
> -    - server_name: 'cicognara-staging.lib'
I think we want this to stay.

2025-01-07 16:11 UTC, acozine commented on group_vars/libstatic/production.yml
> -    - server_name: "cicognara.org"
indeed, the entries in libstatic need to stay

2025-01-07 16:14 UTC, acozine requested changes
Cicognara.org is transferring from a standalone site to an entry in our static sites. We need to get rid of the old standalone infrastructure and automation. We need to keep the automation that relates to its entry in the static sites list, though.

2025-01-07 16:14 UTC, acozine commented on playbooks/cicognara.yml
> -- name: build the cicognara site
This playbook can be deleted entirely. We do not want to build a standalone cicognara site any more.

2025-01-07 16:14 UTC, acozine commented on roles/libstatic/defaults/main.yml
> -    - server_name: 'cicognara-staging.lib'
anything in libstatic should stay

2025-01-07 16:14 UTC, acozine commented on roles/nginxplus/files/conf/http/dev/static_staging.conf
> -server {
these need to stay also

2025-01-13 20:40 UTC, dphillips-39 commented
PR #5714 closes this PR

2025-01-13 20:40 UTC, closed without merging

2025-01-13 20:41 UTC, dphillips-39 commented
retake #5714 replaces this PR